config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  controller :pages do
    get :home
    get :about
    get :contact
  end

  resource :user, only: [:new, :create, :show, :update]

  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: :destroy

  resources :posts, except: :index do
    post '/upvote', to: 'posts#upvote', on: :member
    post '/downvote', to: 'posts#downvote', on: :member
  end

  resources :comments, only: [:new, :create, :show] do
    post '/upvote', to: 'comments#upvote', on: :member
    post '/downvote', to: 'comments#downvote', on: :member
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :text             not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true

  belongs_to :author,
    class_name: "User",
    foreign_key: :author_id

  belongs_to :post

  has_many :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id

  has_many :votes,
    foreign_key: :votable_id,
    dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login!, except: :show

  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  def upvote
    vote(1)
    redirect_to :back
  end

  def downvote
    vote(-1)
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<table>
  <tr>
    <td>
      <%= upvote(comment) %>
    </td>
    <td>
      <strong><%= comment.author.username %></strong>
      <i><%= time_ago_in_words(comment.created_at) %> ago</i>
    </td>
  </tr>
  <tr>
    <td>
      <%= vote_count(comment) %>
    </td>
    <td>
      <%= comment.content %>
    </td>
  </tr>
  <tr>
    <td>
      <%= downvote(comment) %>
    </td>
    <td>
      <%= link_to "Reply", comment_url(comment) %>
    </td>
  </tr>
  <tr>
    <td></td>
    <td>
      <% @comments_by_parent_id[comment.id].each do |child_comment| %>
        <%= render 'comments/comment', comment: child_comment %>
      <% end %>
    </td>
  </tr>
</table>

app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="post">
  <%= authenticity %>

  <input type="hidden"
    name="comment[post_id]"
    value="<%= parent_comment.post_id %>">

  <input type="hidden"
    name="comment[parent_comment_id]"
    value="<%= parent_comment.id %>">

  <div class="form-group">
    <textarea name="comment[content]"
      rows="3" cols="40"
      class="form-control"></textarea>
  </div>

  <button type="submit" class="btn btn-primary">Submit Reply</button>
</form>

app/views/comments/new.html.erb
<div class="row">
  <div class="col-xs-12">

    <h1>Post your comment!</h1>

    <form action="<%= comments_url %>" method="post">
      <%= authenticity %>
      <input type="hidden" name="comment[post_id]" value="<%= params[:post] %>">

      <table>
        <tr>
          <td>
            <textarea name="comment[content]"
              rows="5" cols="40"><%= @comment.content %></textarea>
          </td>
        </tr>
        <tr>
          <td>
            <input type="submit" value="Submit">
          </td>
        </tr>
      </table>
    </form>
  </div>
</div>

app/views/comments/show.html.erb
<div class="row">
  <div class="col-xs-6">

    <% post = @comment.post %>
    <h1><%= link_to post.title, post_url(post) %></h1>

    <p>
      Submitted by <strong><%= post.author.username %></strong>
      <i><%= link_to "#{time_ago_in_words(post.created_at)} ago",
        post.url %></i>
      <br/>
      Subs:
        <% post.subs.each do |sub| %>
          <%= link_to sub.title, sub_url(sub) %>&nbsp;
        <% end %>
    </p>

    <p>
      <%= voting(@comment) %>
      <strong><%= @comment.author.username %></strong>
       <%= time_ago_in_words(@comment.created_at) %> ago
    </p>

    <p><%= @comment.content %></p>

    <%= render 'form', parent_comment: @comment %>
  </div>
</div>