config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  controller :pages do
    get :home
    get :about
    get :contact
  end

  resource :user, only: [:new, :create, :show, :update]

  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: :destroy

  resources :posts, except: :index do
    post '/upvote', to: 'posts#upvote', on: :member
    post '/downvote', to: 'posts#downvote', on: :member
  end

  resources :comments, only: [:new, :create, :show] do
    post '/upvote', to: 'comments#upvote', on: :member
    post '/downvote', to: 'comments#downvote', on: :member
  end
end

app/views/shared/_errors.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">

      <% flash.each do |type, _| %>
        <% flash[type].each do |message| %>
          <div class="alert <%= bootstrap_class_for(type) %> fade in">
            <%= message %>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar nav-default">
  <div class="container-fluid">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#collapse-menu"
            aria-expanded="false">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <div class="collapse navbar-collapse" id="collapse-menu">
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to "Home", home_url %>
      </li>
      <li>
        <%= link_to "About", about_url %>
      </li>
      <li>
        <%= link_to "Contact", contact_url %>
      </li>
      <li>
        <%= link_to "Subs", subs_url %>
      </li>
      <% if logged_in? %>
        <li class="dropdown">
          <a href="#"
            class="dropdown-toggle"
            data-toggle="dropdown"
            role="button"
            aria-haspopup="true"
            aria-expanded="false">
            <%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Profile", user_url %>
            </li>
            <li>
              <%= link_to "Logout", session_url, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", new_session_url %>
        </li>
        <li>
          <%= link_to "Register", new_user_url %>
        </li>
      <% end %>
    </ul>
  </div>

  </div>
</nav>