config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  controller :pages do
    get :home
    get :about
    get :contact
  end

  resource :user, only: [:new, :create, :show, :update]

  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: :destroy

  resources :posts, except: :index do
    post '/upvote', to: 'posts#upvote', on: :member
    post '/downvote', to: 'posts#downvote', on: :member
  end

  resources :comments, only: [:new, :create, :show] do
    post '/upvote', to: 'comments#upvote', on: :member
    post '/downvote', to: 'comments#downvote', on: :member
  end
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true

  belongs_to :moderator,
    class_name: "User"

  has_many :post_subs,
    dependent: :destroy

  has_many :posts,
    through: :post_subs,
    dependent: :destroy
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login!, except: [:index, :show]
  before_action :require_moderator, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  private

  def require_moderator
    moderated_sub = current_user.subs.find(params[:id])
    redirect_to sub_url(params[:id]) unless moderated_sub
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
  def display(sub)
    display = "<strong>#{h(sub.title)}</strong>"
    display += ": "
    display += display_descrip(sub.description) unless sub.description.empty?
    display.html_safe
  end

  def display_descrip(description)
    if description.length > 20
      h(description.slice(0, 20))
    else
      h(description)
    end
  end
end

app/views/subs/_form.html.erb
<% action = (sub.persisted? ? sub_url(sub) : subs_url) %>
<% method = (sub.persisted? ? :patch : :post) %>
<% final_button = (sub.persisted? ? "Update" : "Submit") %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= authenticity %>

  <table>
    <tr>
      <td>
        <label for="sub_title">Sub Title</label>
      </td>
      <td>
        <input type="text"
          name="sub[title]"
          id="sub_title"
          value="<%= sub.title %>">
      </td>
    </tr>
    <tr>
      <td>
        <label for="sub_description">Description</label>
      </td>
      <td>
        <textarea
          name="sub[description]"
          id="sub_description"
          rows="5" cols="40"><%= sub.description %></textarea>
      </td>
    </tr>
  </table>

  <input type="submit" value="<%= final_button %>">
</form>

app/views/subs/edit.html.erb
<div class="row">
  <div class="col-xs-12">

    <h1>Edit Your Sub</h1>

    <%= render 'form', sub: @sub %>
  </div>
</div>

app/views/subs/index.html.erb
<div class="row">
  <div class="col-xs-12">

    <h1>Reddit Clone</h1>

    <p><%= link_to "Create a New Sub", new_sub_url %></p>

    <table class="table">
      <% @subs.each do |sub| %>
        <tr>
          <td>
            <%= link_to display(sub), sub_url(sub), method: :get %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/subs/new.html.erb
<div class="row">
  <div class="col-xs-12">

    <h1>Create a Sub</h1>

    <%= render 'form', sub: @sub %>
  </div>
</div>

app/views/subs/show.html.erb
<div class="row">
  <div class="col-xs-12">

    <h1><%= @sub.title %></h1>

    <p>
      Moderated by <%= @sub.moderator.username %>

      <% if moderator?(@sub) %>
        (<%= link_to "Edit Sub", edit_sub_url, method: :get %>)
      <% end %>
    </p>

    <p><%= @sub.description %></p>

    <h2>Posts</h2>
    <p><%= link_to "Submit Post", new_post_url, method: :get %></p>

    <table>
    <% @sub.posts.each do |post| %>
      <tr>
        <td>
          <%= voting(post) %>
          <strong><%= link_to post.title, post_url(post) %></strong>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
</div>