config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  controller :pages do
    get :home
    get :about
    get :contact
  end

  resource :user, only: [:new, :create, :show, :update]

  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: :destroy

  resources :posts, except: :index do
    post '/upvote', to: 'posts#upvote', on: :member
    post '/downvote', to: 'posts#downvote', on: :member
  end

  resources :comments, only: [:new, :create, :show] do
    post '/upvote', to: 'comments#upvote', on: :member
    post '/downvote', to: 'comments#downvote', on: :member
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :author_id, :title, :subs, presence: true

  belongs_to :author,
    class_name: "User",
    foreign_key: :author_id

  has_many :post_subs,
    dependent: :destroy,
    inverse_of: :post

  has_many :subs,
    through: :post_subs

  has_many :comments,
    dependent: :destroy

  has_many :votes,
    foreign_key: :votable_id,
    dependent: :destroy

  def comments_by_parent_id
    comments_by_parent_id = Hash.new { |h, k| h[k] = [] }

    comments.includes(:author).each do |comment|
      comments_by_parent_id[comment.parent_comment_id] << comment
    end

    comments_by_parent_id
  end

  def subbed?(sub)
    subs.include?(sub)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login!, except: :show
  before_action :require_author, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments_by_parent_id = @post.comments_by_parent_id
    render :show
  end

  def destroy
    @post = Post.destroy(params[:id])
    redirect_to subs_url
  end

  def upvote
    vote(1)
    redirect_to :back
  end

  def downvote
    vote(-1)
    redirect_to :back
  end

  private

  def require_author
    authored_post = current_user.posts.find(params[:id])
    redirect_to post_url(params[:id]) unless authored_post
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def top_level_comments
    @post.comments.where(parent_comment_id: nil)
  end
end

app/views/posts/_form.html.erb
<% action = (post.persisted? ? post_url(post) : posts_url) %>
<% method = (post.persisted? ? :patch : :post) %>
<% final_button = (post.persisted? ? "Update" : "Submit") %>

<div class="col-xs-8">

  <form action="<%= action %>" method="post">
    <input type="hidden" name="_method" value="<%= method %>">
    <%= authenticity %>

    <div class="form-group">
      <label for="post_title">Title</label>
      <input type="text"
        name="post[title]"
        class="form-control"
        id="post_title"
        value="<%= post.title %>">
    </div>

    <div class="form-group">
      <label for="post_url">URL</label>
      <input type="text"
        name="post[url]"
        class="form-control"
        id="post_url"
        value="<%= post.url %>">
    </div>

    <h4>Subs</h4>
    <div id="subs">
      <input type="hidden"
            name="post[sub_ids][]"
            id="sub"
            value="">

      <% Sub.all.each do |sub| %>
        <div class="checkbox">
          <label for="sub">
            <input type="checkbox"
              name="post[sub_ids][]"
              id="sub"
              value="<%= sub.id %>"
              <%= "checked" if post.subbed?(sub) %>>
            <%= sub.title %>
          </label>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <label for="post_content">Content</label>
      <textarea
        name="post[content]"
        id="post_content"
        rows="5"
        style="resize: vertical"
        class="form-control"><%= post.content %></textarea>
    </div>

    <button type="submit"
      class="btn btn-primary">Update Post</button>
  </form>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-xs-12">

    <h1>Edit Your Post</h1>

    <%= render 'form', post: @post %>

  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-xs-12">

    <h1>Make a New Post</h1>

    <%= render 'form', post: @post %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= voting(@post) %> <%= @post.title %></h1>

    <% if author?(@post) %>
      <%= link_to "Edit", edit_post_url, method: :get %> |&nbsp;
      <%= link_to "Delete", post_url(@post), method: :delete %>
    <% end %>

    <p>
      Submitted by <strong><%= @post.author.username %></strong>
      <i><%= link_to "#{time_ago_in_words(@post.created_at)} ago",
        @post.url %></i>
      <br/>
      Subs:
        <% @post.subs.each do |sub| %>
          <%= link_to sub.title, sub_url(sub) %>&nbsp;
        <% end %>
    </p>

    <table>
      <%= @post.content %>
    </table>

    <h3>Comments</h3>

    <p>
      <%= link_to "Post your comment", new_comment_url(post: @post.id) %>
    </p>

    <% @comments_by_parent_id[nil].each do |top_level_comment| %>
      <%= render 'comments/comment', comment: top_level_comment %>
    <% end %>
  </div>
</div>